server:
  port: 8763
spring:
  application:
    name: RubyChinaUploadService
  data:
    neo4j:
      uri: http://localhost:7474/
      username: neo4j
      password: chrome-grand-protect-gentle-catalog-9658
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
